# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - run: yarn test:e2e
    - name: Update Changelog
    - run: |
        npx -q git+ssh://github.com:janhalama/keep-a-changelog.git --release
        export NEW_VERSION=$(npx -q git+ssh://github.com:janhalama/keep-a-changelog.git --latest-release)
        echo "::NEW_VERSION name=NEW_VERSION::${NEW_VERSION}"
    - run: git config --global user.email "mail@janhalama.cz"
    - run: git config --global user.name "GitHub Actions build job"
    - run: git add "CHANGELOG.md"
    - run: git commit -m "docs: update changelog"
    - run: yarn version --new-version ${NEW_VERSION} 
    - run: git push origin && git push --tags
  